%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-gz-ogre-next-vendor
Version:        0.1.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS gz_ogre_next_vendor package

License:        Apache License 2.0 and MIT
URL:            https://www.ogre3d.org/
Source0:        %{name}-%{version}.tar.gz

Requires:       SDL2-devel
Requires:       boost-devel
Requires:       freeimage-devel
Requires:       freetype-devel
Requires:       glslang-devel
Requires:       glslc
Requires:       libX11-devel
Requires:       libXaw-devel
Requires:       libXrandr-devel
Requires:       libatomic
Requires:       libshaderc-devel
Requires:       libxcb-devel
Requires:       mesa-libGL-devel
Requires:       mesa-libGLU-devel
Requires:       poco-devel
Requires:       rapidjson-devel
Requires:       tbb-devel
Requires:       tinyxml2-devel
Requires:       vulkan-headers
Requires:       vulkan-loader-devel
Requires:       zziplib-devel
Requires:       ros-kilted-ros-workspace
BuildRequires:  SDL2-devel
BuildRequires:  boost-devel
BuildRequires:  freeimage-devel
BuildRequires:  freetype-devel
BuildRequires:  glslang-devel
BuildRequires:  glslc
BuildRequires:  libX11-devel
BuildRequires:  libXaw-devel
BuildRequires:  libXrandr-devel
BuildRequires:  libatomic
BuildRequires:  libshaderc-devel
BuildRequires:  libxcb-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  poco-devel
BuildRequires:  rapidjson-devel
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-ament-cmake-vendor-package
BuildRequires:  ros-kilted-gz-cmake-vendor
BuildRequires:  tbb-devel
BuildRequires:  tinyxml2-devel
BuildRequires:  vulkan-headers
BuildRequires:  vulkan-loader-devel
BuildRequires:  zziplib-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-cmake-xmllint
BuildRequires:  ros-kilted-ament-lint-auto
%endif

%description
Vendor package for Ogre-next v2.3.3

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Mon Nov 24 2025 Michael Carroll <mjcarroll@intrinsic.ai> - 0.1.1-1
- Autogenerated by Bloom

* Wed Apr 23 2025 Michael Carroll <mjcarroll@intrinsic.ai> - 0.1.0-2
- Autogenerated by Bloom

